language: python
env:
  global:
    DB_TEST_HOST="localhost"
    DB_TEST_USERNAME="postgres"
    DB_TEST_PASSWORD="root"
    DB_TEST_NAME="fastfoodfast"
    SECRET_KEY = "kiameiieiihig#$%%%^(()_udavhgusk$%#%^******"
    FLASK_APP="run.py"
    APP_SETTINGS="development"

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'CREATE DATABASE fastfoodfast' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls